services:
  - type: web
    name: virginia-crash-data-visualizer
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -c gunicorn.conf.py wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
    healthCheckPath: /
    plan: free
    autoDeploy: true
    repo: https://github.com/yourusername/virginia-crash-visualizer # Replace with your actual repo URL
    branch: main
    description: Interactive visualization of vehicle and pedestrian crash data in Virginia 